import React, {Component} from 'react';
import {Link} from "react-router-dom";

class TermsAndConditions extends Component {
    constructor(props) {
        super(props);
    }//..... end of constructor() .....//

    render() {
        return (
            <>
                <section className="mainCatSection innercatbg" style={{backgroundPosition: 'center left', backgroundColor: 'rgb(132, 132, 132)'}}>
                    <div className="main-overlay" style={{ backgroundColor: 'rgb(177, 235, 0)' ,opacity:0.6 }}>&nbsp;</div>
                    <div className="container">
                        <div className="row">
                            <div className="col-xs-12">
                                <h1>Terms & Conditions <small>BangashAutos</small></h1>
                            </div>
                        </div>
                    </div>
                </section>
                <div className="container" style={{padding: '50px 0px'}}>
                    <div className="row">
                        <div className="col-xs-12">
                            <p>
                                Kindly go through the Terms and Conditions carefully before using BangashAutos.pk.
                                This document is an electronic record relating to Electronic Transactions Ordinance 2002 and rules defined by ETO and the amended versions provided for electronic records in different statutes by the Electronics Transactions Ordinance of 2002.
                                This electronic record is generated by a computer system and thus does not need any physical or digital signatures.
                            </p>
                            <p />
                            <h2>Introduction</h2>
                            <p>
                                BangashAutos.pk, which will be referred to as “Bangash Autos”, “we”, “us” or “Site” later in the document, is an online vendor of car parts and accessories based in Pakistan. Following are the term and conditions defining your access and use of Bangash Autos along with its associated sites, sub-domains, mobile app, and services. By using the Site, you hereby agree to these terms and conditions (and all the content linked within) and show that you will abide by these terms and conditions (the “User Agreement”). This User Agreement is said to be in effect as soon as you start to use the Site and your using the Site represents your agreement with the terms. If you disagree on binding the User Agreement please do not visit, register with or use current Site. This Site is owned and run by &nbsp;Bangash Autos.
                                The Site can, at any time, excise its right of changing, modifying, or removing parts of these Terms and Conditions (T&amp;Cs) without any previous notification. If changes are made in T&amp;Cs, they will be effective as soon as they are posted on the Site. Kindly check the Site reBangasharly for changes in T&amp;Cs. Your further use of the Site after the posting of changes in Terms and Conditions shows your acceptance of those modifications.
                            </p>
                            <h2>Terms of Use </h2>
                            <h4>A) Your Account </h4>
                            <p>
                                To use few specific services offered by this venue, we may ask you to create an account with us or give personal information to complete the registration of your account. We may at any instant under our sole authority and observation invalidate the Account (username and/or password) without giving any prior notice and shall not be accountable for any loss occurred by, suffered by, &nbsp;caused by, happened in the result/request of the invalidation.
                                &nbsp;
                                You have sole responsibility of maintaining confidentiality of your user identification, password, details of account and other relative private information. You agree to undertake the responsibility of ensuring your account and other related information at all times and that you will make sure to take all obligatory actions to prevent misuse of your account. In case you find out your account is being misused or you have revealed your account password to someone unwanted inform us right away. You agree on any misuse of your account and/or its details otherwise will be either be deemed as your responsibility or known to be done under your permission. You agree to be bound by any access of the Site or use of any service from the Site is authorized by you (even when and if it is not). You agree that we will hold only you responsible if such misuse of your account or its details occur. Furthermore you agree to completely indemnify us against any and all losses resulting due to the use of or access to the Site by your account.
                                &nbsp;
                                Please, at all times, make sure that you provide us with correct and complete details. You are to ensure that you update your account details as soon as there are changes in real life. If you cannot update any changes on the site by yourself, our customer service is there to help you out. We may ask you at times to update your details and if you fail to change them in time then your account may be invalidated or withheld under our sole authority and observation and we will not be responsible for any issues or losses incurred due to the invalidation of your account. Thus you agree to change your password every now and then to make sure that your account is secured and also be responsible for the confidentiality of your account and accountable for any disclosure or use (whether you have authorized it or not) of your username and/or password.
                                &nbsp;
                            </p>
                            <h4>B) Privacy</h4>
                            <p>
                                Kindly go through our <strong><Link to={'/privacy-policy'}>Privacy Policy</Link></strong> that is a sub part of this document. The personal information/data that you may give us or your use of this Site creates is strictly confidential, in relevance to the Privacy Agreement and governing laws and reBangashations. If you disagree to your information being used in the way defined in the Privacy Agreement, then please do not access/use/visit the Site.
                            </p>
                            <h4>C) Returns &amp; Refunds</h4>
                            <p>
                                You are to accept the terms of <strong>Return Policy</strong> and <strong>Refund Policy</strong> provided by this Site, kindly review them and then proceed further. If you use our Site and buy our products then you are legally bounded to the rules defined in Return Policy and Refunds Policy. We are not responsible to bear, indemnify or reimburse any losses caused by, incurred by, suffered by our bought products which do not comply with our Return and Refund Policies. You hereby agree to all these policies mentioned if you buy from our Site.
                            </p>
                            <h4>D) Your Conduct</h4>
                            <p>
                                You must not use this platform in ways that can bring harm to Site or anyone accessing the Site (i.e. other users) in form of interruption, damaging or impairing of any kind. You must stay clear of activities that can bring harm to the Site, its staff and all other stake holders and parties directly or indirectly linked with the Site. You know that only you are in question for all electronic communications and data sent from your device to us and you have to use the Site for lawful purposes only. You are to strictly forbidden to:
                            </p><ul>
                            <li>Fake your age, leading to you being under the age of 18 and not an adult.</li>
                            <li>Use this Site for Fraudulent Purposes or any other criminal activities</li>
                            <li>Upload, send, or use/re-use material that is not yours or can hurt or cause harm to anyone else (the Site, its associates or any user using it) or which promotes sexually explicit content, blasphemy, or any other defamatory or abusive material.</li>
                            <li>Harass or Annoy or inconvenience the Site or any individual related to the Site (in any way)</li>
                            <li>Use the site for all other unintended purposes (in ways we don’t want it to be used for)</li>
                        </ul>
                            <p />
                            <h4>E) Trademarks and Copyrights</h4>
                            <p>BangashAutos.PK, Bangash Autos Logo, Bangash Autos, and other such designs shown on the Site are registered trademarks in the specific jurisdiction(s). Our logos, graphic/images, page headers, button icons, and other services are trademarks and should not be used with any product or service that does not come from us. All other trademarks used on the Site are the intellectual property of their actual owners, who may or may not be linked with or sponsored by us.</p>
                            <h4>F) Disclaimer</h4>
                            <p>
                                Hereby you acknowledge that you are using/accessing this Site with your sound mind and understanding and you are purchasing/reselling at your own risk from this venue. We shall not be responsible for any product return or refund if it does not apply to our Site’s <strong>Refund </strong>and <strong>Return</strong> Policies.
                                &nbsp;
                                Resellers may appear on this platform trying to resell their products bought from our site, you must know that we will not be accountable for any losses incurred by or caused by dealing with such individuals (through our Site or elsewhere).
                                &nbsp;
                                We will not be liable for any and all actions and inactions of any other service provider interlinked with our Site’s system including (but not limited to) payment making technologies, installment offerings and Product Shipping companies amongst others.
                            </p>
                        </div>
                    </div>
                </div>

            </>
        );
    }//..... end of render() .....//
}//..... end of TermsAndConditions.

export default TermsAndConditions;
